# The backend Traefik proxy needs to have the timeoutSec increased so it does not close the websocket connection
# This is even the case for active connections
#
# "When sending WebSocket traffic to an HTTP(S) load balancer, the backend service timeout is interpreted
# as the maximum amount of time that a WebSocket, idle or active, can remain open."
# https://cloud.google.com/load-balancing/docs/backend-service#timeout-setting
#
# Enable cookies Stick Sessions so all websocket connections go to the same container
# https://cloud.google.com/kubernetes-engine/docs/how-to/configure-backend-service#setting_generated_cookie_affinity
#
# How to configure a backend config
# https://cloud.google.com/kubernetes-engine/docs/how-to/configure-backend-service
#
# How to use
# kubectl apply -f backend-config.yaml
#
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: config-http
spec:
  timeoutSec: 6000
  sessionAffinity:
    affinityType: 'GENERATED_COOKIE'
