# This is an example .yaml of the required secrets. Uncomment and replace the VALUES with your appropriate base64 encoded string

# apiVersion: v1
# kind: Secret
# metadata:
#   name: db-credentials
# type: Opaque
# data:
#   connectionString: BASE_64_ENCODED_DB_CONNECTION_STRING
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: privateKey
# type: Opaque
# data:
#   access: BASE_64_RSA_PEM
#   refresh: BASE_64_RSA_PEM
