apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.toml: |
    [providers]
      [providers.kubernetesIngress]
        throttleDuration = "10s"
        namespaces = ["default","production"]
        ingressClass = "traefik"

    [log]
      level = "INFO"

    [ping]
      entryPoint = "http"

    [entryPoints]
      [entryPoints.http]
          address = ":80"

    ## Dynamic configuration
    [http.services]
      [http.services.my-service]
        # Sticky sessions for websocket connections
        [http.services.my-service.loadBalancer.sticky.cookie]
          name = "traefik-sticky-session"
          secure = true
          httpOnly = true
