# The specs for the api backend reverse proxy
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: z2p-api
  labels:
    app: z2p-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: z2p-api
        tier: backend
        role: api
    spec:
      restartPolicy: Always
      containers:
        - name: z2p-api
          # The image of the container on google cloud
          image: gcr.io/zero-to-production/z2p-api
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: api.port
            - name: JWT_EXPIRE_TIME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: jwt.expire-time
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token
                  key: access
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token
                  key: refresh
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: connectionString

          readinessProbe:
            ## The port must match the exposed port in the api container
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 60
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: z2p-api-service
  labels:
    app: z2p-api-service
spec:
  selector:
    app: z2p-api
  ports:
    - name: z2p-api-port
      port: 80
      targetPort: 3000
  type: NodePort
